---
title: "GloBI Data Cleaning"
author: "N. Bachelder, A. Chen, Z. Fang, M. Rapaport, S. Solomon"
date: "18 Feb 2021"
output: html_document
---

# To download data for this workflow, please look at our README.md file. These data accessed in September 2021 can be found here: 
# GloBI Community, & Seltmann, Katja C. (2021). Bee Interaction Data from Global Biotic Interactions (2021-09-14_v2) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7753956

# Download the data
```{r}
library(inborutils)

# This function downloads the data as a zip file
# The data will be downloaded to your current working directory. To check your current working directory (and the location where the data will be downloaded), use the function getwd():
getwd()
# You can change your current working directory (and where the data are downloaded), using the setwd() function.
# It takes about 10 min to download the data
download_zenodo(doi = "10.5281/zenodo.7753956")
  # This will download 3 files:
    # all_bee_data_unique.txt.zip
    # globi_bee_data.sh
    # interactions-GloBI-September-14-2021.tsv.gz

# After the data are downloaded, in your browser, navigate to the all_bee_data_unique.txt.zip file that was downloaded
# Double click on the file to unzip
# Once it is unzipped, there will be a new file called: "all_bee_data_unique.txt"
# We will work with that file
```

# Load libraries
```{r}
library(tidyverse)
library(reticulate)

```

# Install python and pandas
```{r}
# path_to_python <- "~/anaconda3/bin/python"
# use_python(path_to_python)
conda_install('r-reticulate', packages = 'pandas')
```
# Filtering
```{python}
import pandas as pd
df = pd.read_csv("all_bee_data_unique.txt", sep='\t', header=0)
```

## Subset
```{python}
# List of total seven of bee families
b_families = ['Andrenidae','Apidae','Colletidae','Halictidae','Megachilidae','Melittidae','Stenotritidae']
# Bee as target, Plant as source
bee_source_df = df.loc[(df['sourceTaxonFamilyName'].isin(b_families)) &
                         (df['targetTaxonKingdomName']=='Plantae')]
# Plant as source, Bee as target
plant_source_df = df.loc[(df['sourceTaxonKingdomName']=='Plantae') &
                           (df['targetTaxonFamilyName'].isin(b_families))]
# Flip target/source for above df
new_col = {}
for col in df.columns:
  if 'source' in col:
    new_col[col] = 'target'+col[6:]
  elif 'target' in col:
    new_col[col] = 'source'+col[6:]
  else:
    new_col[col] = col
plant_source_df = plant_source_df.rename(columns=new_col)
```

## Combine
```{python}
# Combine without dropping duplicates
# The filtering method guarantees two disjoint data frames
interactions_dup = pd.concat([bee_source_df,plant_source_df], axis=0)
# Combine and drop duplicates
interactions = pd.concat([bee_source_df,plant_source_df], axis=0).drop_duplicates()
```

## Result
```{r}
glimpse(py$interactions)
```

# Export to csv.gz file
```{python}
interactions_dup.to_csv("interactions_dup.csv.gz", 
                        index=False, 
                        compression="gzip")
interactions.to_csv("interactions.csv.gz",
                    index=False,
                    compression='gzip')
```
